<?php if ($this->isEnabled('tradedoubler') && $this->getTradedoublerTrackingPixelURL()): ?>
    <!-- Tradedoubler tracking -->
    <img src="<?php print $this->getTradedoublerTrackingPixelURL(); ?>" height="1" width="1" border="0"/>
<?php endif; ?>

<?php if ($this->isEnabled('kelkoo')): ?>
    <!-- Kelkoo code goes here -->
<?php endif; ?>

<?php if ($this->isEnabled('cj')): ?>
    <!-- Comission Junction code goes here -->
<?php endif; ?>
