<?php if ($this->isEnabled('tradedoubler') && $this->getTradedoublerTrackingPixelURL()): ?>
    <!-- Tradedoubler tracking -->
    <img src="<?php print $this->getTradedoublerTrackingPixelURL(); ?>" height="1" width="1" border="0"/>
<?php endif; ?>

<?php if ($this->isEnabled('zanox')): ?>
    <!-- START of the zanox affiliate HTML code -->
    <!-- (The HTML code may not be changed in the sense of faultless functionality!) -->
    <script type="text/javascript" src="https://ad.zanox.com/pps/?<?php print $this->getIntegrationConfig('zanox', 'success_page_mastertag_code'); ?>&mode=[[1]]&CID=[[XXX]]&CustomerID=<?php print $this->getCustomerId(); ?>&OrderID=<?php print $this->getOrderNumber(); ?>?>&CurrencySymbol=<?php print $this->getOrderCurrency(); ?>&TotalPrice=<?php print str_replace('.', ',', $this->getOrderValueIncludingTax()); ?>&PartnerID=<?php print $this->getIntegrationConfig('zanox', 'partner_id'); ?>">
    </script>
    <noscript>
        <img src="https://ad.zanox.com/pps/?<?php print $this->getIntegrationConfig('zanox', 'success_page_mastertag_code'); ?>&mode=[[2]]&CID=[[XXX]]&CustomerID=<?php print $this->getCustomerId(); ?>&OrderID=<?php print $this->getOrderNumber(); ?>&CurrencySymbol=<?php print $this->getOrderCurrency(); ?>&TotalPrice=<?php print str_replace('.', ',', $this->getOrderValueIncludingTax()); ?>&PartnerID=<?php print $this->getIntegrationConfig('zanox', 'partner_id'); ?>" width="1" height="1" />
    </noscript>
    <!-- END zanox-affiliate HTML-Code -->
<?php endif; ?>